# Generated by Django 2.1.8 on 2019-05-26 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherusage',
            name='lat',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='weatherusage',
            name='lng',
            field=models.CharField(max_length=50),
        ),
    ]
