# Generated by Django 2.1.8 on 2019-05-26 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0002_auto_20190526_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherusage',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
